I",
<ul>
  <li><strong>Exception</strong>:
    <ul>
      <li>
        <p>The ValueError raised after typed <code class="highlighter-rouge">pip3 freeze &gt; requirements.txt&gt;</code> and it gave: <code class="highlighter-rouge">ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (c:\users\james\appdata\local\programs\python\python37\lib\site-packages))</code></p>

        <pre class="brush: bash">
  Exception:
  Traceback (most recent call last):
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_vendor\pkg_resources\__init__.py", line 2584, in version
      return self._version
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_vendor\pkg_resources\__init__.py", line 2691, in __getattr__
      raise AttributeError(attr)
  AttributeError: _version

  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_internal\cli\base_command.py", line 176, in main
      status = self.run(options, args)
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_internal\commands\list.py", line 148, in run
      self.output_package_listing(packages, options)
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_internal\commands\list.py", line 205, in output_package_listing
      data, header = format_for_columns(packages, options)
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_internal\commands\list.py", line 271, in format_for_columns
      row = [proj.project_name, proj.version]
    File "c:\users\james\appdata\local\programs\python\python37\lib\site-packages\
  pip\_vendor\pkg_resources\__init__.py", line 2589, in version
      raise ValueError(tmpl % self.PKG_INFO, self)
  ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown
  version] (c:\users\james\appdata\local\programs\python\python37\lib\site-package
  s))		
  </pre>
      </li>
      <li>
        <p>Stackoverflow question <a href="https://stackoverflow.com/questions/54454367/different-error-messages-when-using-pip-install-pip-list-ect">link</a></p>
      </li>
    </ul>
  </li>
  <li>
    <p><strong>root cause</strong>: reffered to [here]((https://github.com/pypa/pip/pull/6225).</p>
  </li>
  <li><strong>howto fix</strong>: for each folder that starts with “-“, delete it and reinstall the corresponding package.</li>
</ul>

:ET